### PR TITLE
make docker image smaller and more robust

### PR DESCRIPTION
**Pull request by ibotty**

### CODE REVIEW

**Comment by lennardk** [comment]
I'm not sure `pip install -e`-ing from /tmp is a very sensible thing to do, as all `pip install -e` does is create `site-packages/easy-install` and `site-packages/taiga-contrib-openid-auth.egg-link`, both pointing to the `/tmp` path

**Comment by ibotty** [comment]
No, it installs in `/opt/venv/lib/python3.7/site-packages`.

**Comment by lennardk** [comment]
I think `pip install /tmp/taiga-contrib-openid-auth*/back && rm -R /tmp/taiga-contrib-openid-auth*` would do the trick yes, although I haven't tested it myself.

**Comment by ibotty** [comment]
What do you think?  I am running a container built like this (but based on some pull requests on the taiga-docker repos) in production.

**Comment by lennardk** [comment]
looks good to me, but I'm not a maintainer. @ralphbean looks like the right person to accept :)

**Pull request merged**
